spring:
  datasource:
    url: jdbc:postgresql://ewm-db:5432/ewm
    driverClassName: org.postgresql.Driver
    username: ewmuser
    password: 12345
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
server:
  port: 8080

ru.practicum.stats-client:
  server:
    host: stats-server
    port: 9090