services:
  stats:
    image: postgres:16.1
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: 12345
    ports:
      - "5434:5432"
    volumes:
      - stats-data:/var/lib/postgresql/data

  stats-server:
    build:
      context: .
      dockerfile: stats/server/Dockerfile
    ports:
      - "9090:9090"

  ewm-db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: ewm
      POSTGRES_USER: ewmuser
      POSTGRES_PASSWORD: 12345
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ewm-service:
    build:
      context: .
      dockerfile: ewm-service/Dockerfile
    ports:
      - "8080:8080"


volumes:
  stats-data:
  postgres_data:

